// Mocks generated by Mockito 5.4.6 from annotations
// in resto_app_dicoding/test/resto_list_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:resto_app_dicoding/data/api/api_service.dart' as _i2;
import 'package:resto_app_dicoding/data/local/local_databaser_service.dart'
    as _i3;
import 'package:resto_app_dicoding/data/models/restaurant_detail_model.dart'
    as _i4;
import 'package:resto_app_dicoding/data/models/restaurant_item_model.dart'
    as _i7;
import 'package:resto_app_dicoding/data/models/review_model.dart' as _i8;
import 'package:resto_app_dicoding/data/repositories/restaurant_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalDatabaserService_1 extends _i1.SmartFake
    implements _i3.LocalDatabaserService {
  _FakeLocalDatabaserService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRestaurantDetail_2 extends _i1.SmartFake
    implements _i4.RestaurantDetail {
  _FakeRestaurantDetail_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RestaurantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantRepository extends _i1.Mock
    implements _i5.RestaurantRepository {
  MockRestaurantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  _i3.LocalDatabaserService get databaseServices =>
      (super.noSuchMethod(
            Invocation.getter(#databaseServices),
            returnValue: _FakeLocalDatabaserService_1(
              this,
              Invocation.getter(#databaseServices),
            ),
          )
          as _i3.LocalDatabaserService);

  @override
  _i6.Future<List<_i7.RestaurantItem>> getRestaurantList() =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantList, []),
            returnValue: _i6.Future<List<_i7.RestaurantItem>>.value(
              <_i7.RestaurantItem>[],
            ),
          )
          as _i6.Future<List<_i7.RestaurantItem>>);

  @override
  _i6.Future<_i4.RestaurantDetail> getRestaurantDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantDetail, [id]),
            returnValue: _i6.Future<_i4.RestaurantDetail>.value(
              _FakeRestaurantDetail_2(
                this,
                Invocation.method(#getRestaurantDetail, [id]),
              ),
            ),
          )
          as _i6.Future<_i4.RestaurantDetail>);

  @override
  _i6.Future<List<_i7.RestaurantItem>> searchRestaurant(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchRestaurant, [query]),
            returnValue: _i6.Future<List<_i7.RestaurantItem>>.value(
              <_i7.RestaurantItem>[],
            ),
          )
          as _i6.Future<List<_i7.RestaurantItem>>);

  @override
  _i6.Future<List<_i8.Review>> addReview({
    required String? restaurantId,
    required String? name,
    required String? review,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addReview, [], {
              #restaurantId: restaurantId,
              #name: name,
              #review: review,
            }),
            returnValue: _i6.Future<List<_i8.Review>>.value(<_i8.Review>[]),
          )
          as _i6.Future<List<_i8.Review>>);

  @override
  _i6.Future<void> saveBookmark(_i7.RestaurantItem? restaurant) =>
      (super.noSuchMethod(
            Invocation.method(#saveBookmark, [restaurant]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeBookmark(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeBookmark, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.RestaurantItem>> getBookmarkedRestaurants() =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkedRestaurants, []),
            returnValue: _i6.Future<List<_i7.RestaurantItem>>.value(
              <_i7.RestaurantItem>[],
            ),
          )
          as _i6.Future<List<_i7.RestaurantItem>>);

  @override
  _i6.Future<bool> isBookmarked(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isBookmarked, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
